language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
branches:
  only: 
    - master
    - develop
script:
  - dotnet restore
  - dotnet build